# Generated by Django 5.1.2 on 2024-12-23 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('skills_1', models.CharField(max_length=100)),
                ('skills_2', models.CharField(max_length=100)),
                ('skills_3', models.CharField(max_length=100)),
                ('skills_4', models.CharField(max_length=100)),
                ('experience_1_title', models.CharField(max_length=100)),
                ('experience_1_dur', models.CharField(max_length=100)),
                ('experience_1_desc', models.TextField()),
                ('experience_2_title', models.CharField(blank=True, max_length=100, null=True)),
                ('experience_2_dur', models.CharField(blank=True, max_length=100, null=True)),
                ('experience_2_desc', models.TextField(blank=True, null=True)),
                ('education_1', models.CharField(max_length=100)),
                ('education_1_dur', models.CharField(max_length=100)),
                ('education1_score', models.CharField(max_length=50)),
                ('education_2', models.CharField(blank=True, max_length=100, null=True)),
                ('education_2_dur', models.CharField(blank=True, max_length=100, null=True)),
                ('education2_score', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
